# Generated by Django 4.0.5 on 2022-06-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arte_todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
