# Generated by Django 4.0.5 on 2022-06-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arte_todo', '0002_foto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='foto'),
        ),
    ]
