# Generated by Django 4.0.5 on 2022-06-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arte_todo', '0003_alter_foto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('contacto', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='consulta',
        ),
    ]
