# Generated by Django 4.0.5 on 2022-06-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arte_todo', '0004_contacto_delete_consulta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacto',
            new_name='consulta',
        ),
    ]
