# Generated by Django 4.0.5 on 2022-06-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arte_todo', '0006_remove_consulta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(upload_to='foto'),
        ),
    ]
