# Generated by Django 4.0.5 on 2022-07-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arte_todo', '0007_alter_foto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='asunto',
            field=models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia']]),
        ),
    ]
